var xgwss="wss://zhibo3.yuexiawang.com";
var xgurl="";
var xgsqurl="https://api.49lhapi.com/api/web/lottery/lastLotteryRecord?lotteryType=1";
var xawss="wss://zhibo.yuexiawang.com";
var xaurl="";
var xasqurl="https://api.49lhapi.com/api/web/lottery/lastLotteryRecord?lotteryType=2";
var laurl1="https://a6tkapi1.com/gallerynew/h5/index/lastLotteryRecord?lotteryType=2";
var laurl2="https://live2.lhzzcenter.com/livedata/data_mo.json";
var laurl3="https://live.lhzzcenter.com/livedata/data_mo.json";
